### ISSUE TITLE
Find and document enclosure assumptions for commercial template model

### ISSUE THREAD

**Issue by mchaf0126** [mchaf0126/pod_lca_scenario_explorer#100]

**Comment by stephcarlisle** [comment]
Envelope options in Kalidescope Reviewed. 10 design options were selected for inclusion in the template model. Can be expanded at a later date, if we want, but this probably covers the bases pretty nicely. Existing design options in the M3.1 model are also included in this set. 
Write up: https://docs.google.com/document/d/1gTB0hfQk5Ju7TlS70Rm5IwDwwgSS7QpY1yOIgRKxKJY/edit
Envelope spreadsheet: https://docs.google.com/spreadsheets/d/19uBDLrJPGaAQ9O9IHpaCr8Kv8n0Nij8Oub_FJzqEG_o/edit?gid=1465507455#gid=1465507455

**Comment by mchaf0126** [comment]
awesome! this will be so useful :)
