### ISSUE TITLE
Identify potential sources for transportation databases

### ISSUE THREAD

**Issue by mchaf0126** [mchaf0126/pod_lca_scenario_explorer#89]

**Comment by mchaf0126** [comment]
Per 10/8 call, make sure to document different units correspond to which databases as well

**Comment by mchaf0126** [comment]
@Mhtaba76 Hey Mo, do you have an update on this issue? Hoping to get it closed out before the end of the week. Let me know if you have any questions.

**Comment by Mhtaba76** [comment]
@mchaf0126 Hi Mel, I'm documenting the sources and will add the link here within a few hours.

**Comment by Mhtaba76** [comment]
@mchaf0126 @stephcarlisle See this [document ](https://docs.google.com/document/d/11W_E2VqkItKfP8LyDPUI21zGu1nPB4yBWtrviUDHZa4/edit?usp=sharing)

**Comment by mchaf0126** [comment]
Looks like the Materials team will be taking this kind of work over. Let's close this issue for now.
