### ISSUE TITLE
Identify potential sources for replacement databases

### ISSUE THREAD

**Issue by mchaf0126** [mchaf0126/pod_lca_scenario_explorer#92]

**Comment by kiunana** [comment]
@mchaf0126 @stephcarlisle See doc added herehttps://docs.google.com/document/d/107xA9jqJ1mrnRmRRFBudW7x9DQP_elYQgowDAsCcYXA/edit?usp=sharing

**Comment by mchaf0126** [comment]
This looks good to me!
