### ISSUE TITLE
Download and convert replacement  databases into planned schema

### ISSUE THREAD

**Issue by mchaf0126** [mchaf0126/pod_lca_scenario_explorer#93]

**Comment by kiunana** [comment]
- [ ] Double check type in ASHRAE_service_life with OmniClass table 21
[10/15/2024: No ASHRAE_mapper required. Template models (in REVIT) will be built with OmniClass Level 3, which is used in ASHRAE Service live]

**Comment by kiunana** [comment]
@mchaf0126 clarification needed for RICS_mapper:
- ids 7-9, 11 ---are these integral to the floor or the finishes (i.e., therefore be classified as 'Superstructure: Structural elements' or 'Floor finishes')
- ids 18-25 --- Are these facade or internal partitioning? Are these structural walls (Assumed that 16 and 17 are structural walls)?

**Comment by mchaf0126** [comment]
Hey Isuru, I did not see this. Which is a bummer. 

Ids7-9, 11 are superstructure: structural elements. 
ids 16-19 are footings, so they are part of the foundation. 
ids 20-21 are structural beams, so they're part of the superstructure
ids 22-23 are structural walls
ids 24-33 are the facade.

Let me know if you need more info

**Comment by mchaf0126** [comment]
closed with #93
